"""clients_contacts_softdelete_and_timestamps

Revision ID: 15a0067971e8
Revises: 5573e3bbd9ff
Create Date: 2025-09-04 09:21:07.749974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a0067971e8'
down_revision: Union[str, None] = '5573e3bbd9ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_contacts', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('client_contacts', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('clients', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('clients', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'active')
    op.drop_column('clients', 'updated_at')
    op.drop_column('client_contacts', 'active')
    op.drop_column('client_contacts', 'updated_at')
    # ### end Alembic commands ###
