"""add_company_to_vehicles_and_orders

Revision ID: 227a2d640792
Revises: fb869cc239e4
Create Date: 2025-09-03 12:33:41.016511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '227a2d640792'
down_revision: Union[str, None] = 'fb869cc239e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_orders', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_service_orders_company_id'), 'service_orders', ['company_id'], unique=False)
    op.create_foreign_key(None, 'service_orders', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.add_column('vehicles', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_vehicles_company_id'), 'vehicles', ['company_id'], unique=False)
    op.create_foreign_key(None, 'vehicles', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_index(op.f('ix_vehicles_company_id'), table_name='vehicles')
    op.drop_column('vehicles', 'company_id')
    op.drop_constraint(None, 'service_orders', type_='foreignkey')
    op.drop_index(op.f('ix_service_orders_company_id'), table_name='service_orders')
    op.drop_column('service_orders', 'company_id')
    # ### end Alembic commands ###
