"""client_contacts_and_updated_by

Revision ID: 5573e3bbd9ff
Revises: a14225e1042f
Create Date: 2025-09-04 09:07:06.883791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5573e3bbd9ff'
down_revision: Union[str, None] = 'a14225e1042f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('cargo', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_contacts_client_id'), 'client_contacts', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_contacts_created_by_user_id'), 'client_contacts', ['created_by_user_id'], unique=False)
    op.add_column('clients', sa.Column('updated_by_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_clients_updated_by_user_id'), 'clients', ['updated_by_user_id'], unique=False)
    op.create_foreign_key(None, 'clients', 'users', ['updated_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_index(op.f('ix_clients_updated_by_user_id'), table_name='clients')
    op.drop_column('clients', 'updated_by_user_id')
    op.drop_index(op.f('ix_client_contacts_created_by_user_id'), table_name='client_contacts')
    op.drop_index(op.f('ix_client_contacts_client_id'), table_name='client_contacts')
    op.drop_table('client_contacts')
    # ### end Alembic commands ###
