"""hseq_hr

Revision ID: 91157e3b249c
Revises: fda8900aa6c3
Create Date: 2025-08-27 06:44:12.324647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91157e3b249c'
down_revision: Union[str, None] = 'fda8900aa6c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('vencimiento', sa.Date(), nullable=True),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.Column('firmado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_docs_operator_id'), 'employee_docs', ['operator_id'], unique=False)
    op.create_table('inductions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('tema', sa.String(length=160), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('aprobado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inductions_operator_id'), 'inductions', ['operator_id'], unique=False)
    op.create_table('preop_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('resultado', sa.String(length=40), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preop_inspections_vehicle_id'), 'preop_inspections', ['vehicle_id'], unique=False)
    op.create_table('hseq_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=80), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('evidencias', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['service_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hseq_events')
    op.drop_index(op.f('ix_preop_inspections_vehicle_id'), table_name='preop_inspections')
    op.drop_table('preop_inspections')
    op.drop_index(op.f('ix_inductions_operator_id'), table_name='inductions')
    op.drop_table('inductions')
    op.drop_index(op.f('ix_employee_docs_operator_id'), table_name='employee_docs')
    op.drop_table('employee_docs')
    # ### end Alembic commands ###
