"""clients_company_creator

Revision ID: a14225e1042f
Revises: 227a2d640792
Create Date: 2025-09-03 17:00:43.909810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a14225e1042f'
down_revision: Union[str, None] = '227a2d640792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_clients_company_id'), 'clients', ['company_id'], unique=False)
    op.create_index(op.f('ix_clients_created_by_user_id'), 'clients', ['created_by_user_id'], unique=False)
    op.create_foreign_key(None, 'clients', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'clients', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_index(op.f('ix_clients_created_by_user_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_company_id'), table_name='clients')
    op.drop_column('clients', 'created_by_user_id')
    op.drop_column('clients', 'company_id')
    # ### end Alembic commands ###
