"""crm

Revision ID: f37e6cb4ad93
Revises: bf6e1d747348
Create Date: 2025-08-26 16:32:07.876432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37e6cb4ad93'
down_revision: Union[str, None] = 'bf6e1d747348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nit', sa.String(length=30), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('ubicaciones', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_nit'), 'clients', ['nit'], unique=True)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('fuente', sa.String(length=50), nullable=True),
    sa.Column('industria_id', sa.Integer(), nullable=True),
    sa.Column('residuos', sa.JSON(), nullable=True),
    sa.Column('cobertura', sa.String(length=120), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['industria_id'], ['industries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_client_id'), 'leads', ['client_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('valor_estimado', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('probabilidad', sa.Float(), nullable=True),
    sa.Column('etapa', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_lead_id'), 'opportunities', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunities_lead_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_leads_client_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_clients_nit'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
