"""ops_add_user_and_primary_vehicle

Revision ID: f395dd048dc8
Revises: 313a7f23bf53
Create Date: 2025-08-29 23:58:05.628724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f395dd048dc8'
down_revision: Union[str, None] = '313a7f23bf53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operators', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('operators', sa.Column('primary_vehicle_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_operators_primary_vehicle_id'), 'operators', ['primary_vehicle_id'], unique=False)
    op.create_index(op.f('ix_operators_user_id'), 'operators', ['user_id'], unique=False)
    op.create_foreign_key(None, 'operators', 'vehicles', ['primary_vehicle_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'operators', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operators', type_='foreignkey')
    op.drop_constraint(None, 'operators', type_='foreignkey')
    op.drop_index(op.f('ix_operators_user_id'), table_name='operators')
    op.drop_index(op.f('ix_operators_primary_vehicle_id'), table_name='operators')
    op.drop_column('operators', 'primary_vehicle_id')
    op.drop_column('operators', 'user_id')
    # ### end Alembic commands ###
