"""vehicle_type_company_scope

Revision ID: fb869cc239e4
Revises: f395dd048dc8
Create Date: 2025-09-01 14:23:58.555903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb869cc239e4'
down_revision: Union[str, None] = 'f395dd048dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_types', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_vehicle_types_company_id'), 'vehicle_types', ['company_id'], unique=False)
    op.create_foreign_key(None, 'vehicle_types', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicle_types', type_='foreignkey')
    op.drop_index(op.f('ix_vehicle_types_company_id'), table_name='vehicle_types')
    op.drop_column('vehicle_types', 'company_id')
    # ### end Alembic commands ###
