"""quotes_send_accept

Revision ID: fda8900aa6c3
Revises: 956bfb86d565
Create Date: 2025-08-27 06:14:09.061993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fda8900aa6c3'
down_revision: Union[str, None] = '956bfb86d565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quotations', sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotations', 'accepted_at')
    op.drop_column('quotations', 'sent_at')
    # ### end Alembic commands ###
